"""User authentication

Revision ID: 73d42b5e6da5
Revises: 
Create Date: 2025-01-31 19:04:25.091185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73d42b5e6da5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('practice_level_prescribing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('practice', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('items', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.alter_column('SHA',
               existing_type=sa.TEXT(),
               type_=sa.String(length=3),
               existing_nullable=True)
        batch_op.alter_column('PCT',
               existing_type=sa.TEXT(),
               type_=sa.String(length=3),
               existing_nullable=True)
        batch_op.alter_column('BNFCODE',
               existing_type=sa.TEXT(),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('BNFNAME',
               existing_type=sa.REAL(),
               type_=sa.String(length=40),
               existing_nullable=True)
        batch_op.alter_column('NIC',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('ACTCOST',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('PRACTICE')
        batch_op.drop_column('ID')
        batch_op.drop_column('ITEMS')
        batch_op.drop_column('QUANTITY')

    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('practice_code', sa.String(length=6), nullable=False))
        batch_op.add_column(sa.Column('practice_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_line_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_line_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('county', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('post_code', sa.String(length=10), nullable=True))
        batch_op.drop_column('POSTCODE')
        batch_op.drop_column('ADDRESS1')
        batch_op.drop_column('PRACTICE')
        batch_op.drop_column('AREA')
        batch_op.drop_column('ADDRESS2')
        batch_op.drop_column('CITY')
        batch_op.drop_column('CODE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CODE', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('CITY', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ADDRESS2', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('AREA', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('PRACTICE', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ADDRESS1', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('POSTCODE', sa.TEXT(), nullable=True))
        batch_op.drop_column('post_code')
        batch_op.drop_column('county')
        batch_op.drop_column('city')
        batch_op.drop_column('address_line_2')
        batch_op.drop_column('address_line_1')
        batch_op.drop_column('practice_name')
        batch_op.drop_column('practice_code')

    with op.batch_alter_table('practice_level_prescribing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('QUANTITY', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ITEMS', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ID', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('PRACTICE', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, 'practices', ['PRACTICE'], ['CODE'])
        batch_op.alter_column('ACTCOST',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('NIC',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('BNFNAME',
               existing_type=sa.String(length=40),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('BNFCODE',
               existing_type=sa.String(length=15),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('PCT',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('SHA',
               existing_type=sa.String(length=3),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('quantity')
        batch_op.drop_column('items')
        batch_op.drop_column('practice')
        batch_op.drop_column('id')

    op.drop_table('user')
    # ### end Alembic commands ###
